import Head from 'next/head'
import Footer from '../components/Footer'
import Gallery from '../components/Gallery'
import Hero from '../components/Hero'
import Info from '../components/Info'
import Menu from '../components/Menu'
import Reviews from '../components/Reviews'
import Table from '../components/Table'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Luxury Restaurant</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<Menu />
			<Table />
			<Reviews />
			<Gallery />
			<Info />
			<Footer />
		</div>
	)
}
